parent=keycloak
styles=css/caselaw-login.css
footerBissLabel=${env.CASELAW_AUTH_FOOTER_BISS_LABEL:BISS Institute}
footerBissUrl=${env.CASELAW_AUTH_FOOTER_BISS_URL:https://www.maastrichtuniversity.nl/research/brightlands-institute-smart-society}
footerLawTechLabel=${env.CASELAW_AUTH_FOOTER_LAW_TECH_LABEL:Maastricht University Law & Tech Lab}
footerLawTechUrl=${env.CASELAW_AUTH_FOOTER_LAW_TECH_URL:https://www.maastrichtuniversity.nl/research/law-and-tech-lab}
footerApiLabel=${env.CASELAW_AUTH_FOOTER_API_LABEL:Citations API}
footerApiUrl=${env.CASELAW_AUTH_FOOTER_API_URL:https://demo-api.caselawexplorer.tech}
